### ISSUE TITLE
Cant get minimal-open-modelica:latest

### ISSUE THREAD

**Issue by Elfangor93** [creative-connections/Bodylight.js-OM-Compiler#3]
I tried to use the OM-Compiler. Docker is installed and running on a Windows 10 machine. If I try to do `docker build -t bodylight.js.om.compiler .` in PowerShell (administrator) inside the folder "Bodylight.js-OM-Compiler" I get:
`Sending build context to Docker daemon  52.74kB
Step 1/6 : FROM creativeconnections/minimal-open-modelica:latest
Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Comment by david-polak** [comment]
There seems to be a lot of issues related to this in docker.

Check out [this one](https://github.com/docker/for-win/issues/611) or [this one](https://forums.docker.com/t/error-response-from-daemon-get-https-registry-1-docker-io-v2/23741/4) and see if any of it helps.

**Comment by Elfangor93** [comment]
Yes, changing of the DNS of the Ethernet Adapter of docker to 8.8.8.8 solved the problem...
Thanks!
